import Link from 'next/link'
import { ArrowRight, Check } from 'lucide-react'
import { insights, services, site } from '@/lib/site-content'

export function Eyebrow({ children }: { children: React.ReactNode }) { return <p className="font-mono text-xs font-bold uppercase tracking-[0.2em] text-accent-foreground">{children}</p> }
export function SectionHeading({ eyebrow, title, body }: { eyebrow: string; title: string; body?: string }) { return <div className="flex max-w-3xl flex-col gap-5"><Eyebrow>{eyebrow}</Eyebrow><h2 className="text-balance font-sans text-4xl font-semibold tracking-tight md:text-6xl">{title}</h2>{body && <p className="max-w-2xl text-pretty text-lg leading-relaxed text-muted-foreground">{body}</p>}</div> }
export function PageIntro({ eyebrow, title, copy }: { eyebrow: string; title: string; copy: string }) { return <section className="border-b border-border px-5 py-16 md:py-24 lg:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-6"><Eyebrow>{eyebrow}</Eyebrow><h1 className="max-w-4xl text-balance text-5xl font-semibold tracking-tight md:text-7xl">{title}</h1><p className="max-w-2xl text-pretty text-lg leading-relaxed text-muted-foreground">{copy}</p></div></section> }
export function ServiceGrid() { return <div className="grid border-l border-t border-border md:grid-cols-2">{services.map((service, i) => { const Icon = service.icon; return <Link href={`/services/${service.slug}`} key={service.slug} className="group flex min-h-80 flex-col justify-between border-b border-r border-border p-7 transition-colors hover:bg-muted md:p-10"><div className="flex items-start justify-between"><span className="font-mono text-xs text-muted-foreground">0{i + 1}</span><Icon className="size-6 text-primary" aria-hidden="true" /></div><div className="flex flex-col gap-4"><h3 className="text-2xl font-semibold">{service.title}</h3><p className="leading-relaxed text-muted-foreground">{service.short}</p><span className="flex items-center gap-2 text-sm font-bold">Explore capability <ArrowRight className="size-4 transition-transform group-hover:translate-x-1" aria-hidden="true" /></span></div></Link>})}</div> }
export function InsightGrid() { return <div className="grid gap-5 md:grid-cols-3">{insights.map((item, i) => <Link key={item.slug} href={`/insights/${item.slug}`} className="group flex min-h-96 flex-col justify-between rounded-3xl border border-border bg-card p-7 transition-transform hover:-translate-y-1"><div className={`editorial-tile tile-${i + 1}`} aria-hidden="true"><span>{item.category}</span></div><div className="flex flex-col gap-3"><p className="font-mono text-xs uppercase tracking-wider text-muted-foreground">{item.date} · {item.read}</p><h3 className="text-balance text-xl font-semibold leading-snug">{item.title}</h3><p className="text-sm leading-relaxed text-muted-foreground">{item.excerpt}</p></div></Link>)}</div> }
export function CTA({ title = 'Ready to turn priorities into progress?', body = 'Start with a focused conversation about what is getting in the way of growth.' }: { title?: string; body?: string }) { return <section className="bg-primary text-primary-foreground"><div className="mx-auto flex max-w-7xl flex-col gap-8 px-5 py-16 md:flex-row md:items-end md:justify-between lg:px-8 lg:py-24"><div className="flex max-w-3xl flex-col gap-5"><p className="font-mono text-xs font-bold uppercase tracking-[0.2em] text-primary-foreground/65">Start a conversation</p><h2 className="text-balance text-4xl font-semibold tracking-tight md:text-6xl">{title}</h2><p className="max-w-xl text-lg leading-relaxed text-primary-foreground/75">{body}</p></div><a href={site.bookingUrl} target="_blank" rel="noreferrer" className="flex w-fit shrink-0 items-center gap-3 rounded-full bg-background px-6 py-4 font-bold text-foreground">Book a discovery call <ArrowRight className="size-4" aria-hidden="true" /></a></div></section> }
export function Checklist({ items }: { items: string[] }) { return <ul className="flex flex-col gap-3">{items.map(item => <li key={item} className="flex items-start gap-3"><span className="mt-1 flex size-5 shrink-0 items-center justify-center rounded-full bg-secondary text-secondary-foreground"><Check className="size-3" aria-hidden="true" /></span><span className="leading-relaxed text-muted-foreground">{item}</span></li>)}</ul> }
