import type { Metadata } from 'next'
import { notFound } from 'next/navigation'
import Link from 'next/link'
import { ArrowLeft } from 'lucide-react'
import { CTA, Checklist } from '@/components/marketing'
import { services } from '@/lib/site-content'
export function generateStaticParams(){return services.map(s=>({slug:s.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const s=services.find(x=>x.slug===slug);return s?{title:s.title,description:s.short}:{}}
export default async function ServicePage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const service=services.find(s=>s.slug===slug);if(!service)notFound();const Icon=service.icon;return <main id="main-content"><section className="hero-grid border-b border-border"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><Link href="/services" className="mb-10 flex w-fit items-center gap-2 text-sm font-bold"><ArrowLeft className="size-4"/>All services</Link><div className="grid gap-10 lg:grid-cols-[1fr_.35fr]"><div className="flex max-w-4xl flex-col gap-6"><p className="font-mono text-xs font-bold uppercase tracking-[.2em] text-accent-foreground">Capability</p><h1 className="text-balance text-5xl font-semibold tracking-[-.045em] md:text-7xl">{service.title}</h1><p className="max-w-2xl text-xl leading-relaxed text-muted-foreground">{service.short}</p></div><div className="flex aspect-square items-center justify-center rounded-[2.5rem] bg-primary text-primary-foreground"><Icon className="size-24"/></div></div></div></section><section className="mx-auto grid max-w-7xl gap-14 px-5 py-20 lg:grid-cols-2 lg:px-8 lg:py-28"><div><p className="mb-5 font-mono text-xs uppercase tracking-widest text-accent-foreground">What this can include</p><h2 className="text-4xl font-semibold">Work shaped around the commercial need.</h2></div><Checklist items={service.includes}/></section><section className="bg-muted"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><p className="max-w-4xl text-balance text-3xl font-semibold leading-snug md:text-5xl">Prospertia can deliver directly, lead the right specialists, or combine this capability into an ongoing Growth Partner programme.</p></div></section><CTA title={`Want to improve your ${service.title.toLowerCase()}?`}/></main>}
