import type { Metadata } from 'next'
import { notFound } from 'next/navigation'
import Link from 'next/link'
import { ArrowLeft } from 'lucide-react'
import { CTA } from '@/components/marketing'
import { insights } from '@/lib/site-content'
const articleCopy:Record<string,string[]>={
'growth-exposes-gaps':['Most growing businesses do not wake up one morning with a broken commercial system. The gaps arrive gradually, then growth makes them visible.','Marketing adds tools to solve immediate needs. Sales creates its own materials. The website reflects an earlier version of the business. CRM activity grows, but shared discipline does not. Each choice is understandable on its own; together, they create friction.','The answer is not automatically another platform or agency. Start by identifying the commercial objective, mapping the full journey, and agreeing which constraint matters most. Joined-up priorities beat disconnected activity.'],
'getting-more-from-hubspot':['HubSpot cannot fix a process nobody has agreed. Before building another workflow, decide what sales and marketing need the system to make easier.','Look at ownership, lifecycle definitions, handovers, campaign decisions and reporting questions. If leadership cannot describe these clearly, more technical complexity usually creates more maintenance rather than more value.','A useful CRM is an operating habit supported by technology. Simplify the process, make ownership explicit, then configure the platform around the work people actually need to do.'],
'practical-ai-plan':['The strongest AI opportunities are rarely found by starting with a list of tools. They are found by looking carefully at work.','Find tasks that are repetitive, slow, inconsistent or dependent on information being copied between systems. Then assess the risk, judgement and context each task requires. Some work can be automated. Some can be accelerated. Some should remain deliberately human.','A practical plan turns a small number of clear use cases into tested workflows, owners and measures of success. Adoption follows useful work — not novelty.']}
export function generateStaticParams(){return insights.map(i=>({slug:i.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const a=insights.find(x=>x.slug===slug);return a?{title:a.title,description:a.excerpt}:{}}
export default async function ArticlePage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const article=insights.find(i=>i.slug===slug);if(!article)notFound();return <main id="main-content"><article><header className="border-b border-border"><div className="mx-auto max-w-4xl px-5 py-20 lg:py-28"><Link href="/insights" className="mb-12 flex w-fit items-center gap-2 text-sm font-bold"><ArrowLeft className="size-4"/>All insights</Link><p className="font-mono text-xs uppercase tracking-widest text-accent-foreground">{article.category}</p><h1 className="mt-6 text-balance text-5xl font-semibold tracking-[-.04em] md:text-7xl">{article.title}</h1><p className="mt-7 text-lg text-muted-foreground">{article.date} · {article.read}</p></div></header><div className="mx-auto flex max-w-3xl flex-col gap-7 px-5 py-20 text-lg leading-[1.8] text-muted-foreground">{articleCopy[slug].map((p,i)=><p key={i} className={i===0?'text-2xl font-medium leading-relaxed text-foreground':''}>{p}</p>)}</div></article><CTA/></main>}
